CREATE DATABASE IF NOT EXISTS test;

USE test;

CREATE TABLE IF NOT EXISTS currency_exchange
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE_TIME TIMESTAMP NOT NULL,
    EUR_BUY   DOUBLE    NOT NULL,
    EUR_SELL  DOUBLE    NOT NULL,
    USD_BUY   DOUBLE    NOT NULL,
    USD_SELL  DOUBLE    NOT NULL
);
